# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - automation
      - dependabot
    allow:
      - dependency-name: "github.com/bwmarrin/discordgo"
      - dependency-name: "go.uber.org/*"
      - dependency-name: "github.com/go-json-experiment/*"
    groups:
      bwmarrin-projects:
        patterns:
          - "github.com/bwmarrin/*"
      uber:
        patterns:
          - "go.uber.org/*"
      go-json-experiment:
        patterns:
          - "github.com/go-json-experiment/*"
      
    open-pull-requests-limit: 2
