apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bender
  namespace: bender-system
spec:
  project: bender
  source:
    repoURL: https://github.com/zmoog/go-bender
    targetRevision: HEAD
    path: zarf/k8s/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: bender-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
