apiVersion: v1
kind: Namespace
metadata:
  name: bender-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bender
  namespace: bender-system
spec:
  selector:
    matchLabels:
      app: bender
  template:
    metadata:
      labels:
        app: bender
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: bender-bot
        image: service-image

        env:
        - name: DISCORD_TOKEN
          value: "<your Discord token here>"
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
