apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/bender
patches:
- path: dev-bender-patch-deployment.yaml
images:
- name: service-image
  newName: zmoog/bender
  newTag: 0.2.0-pre1
